name: Build PPTP IPK

on:
  push:
    branches: [ main ]

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OpenWrt SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev unzip python3
          SDK_URL="https://downloads.openwrt.org/releases/21.02.7/targets/ramips/mt7621/openwrt-sdk-21.02.7-ramips-mt7621_gcc-8.4.0_musl.Linux-x86_64.tar.xz"
          wget $SDK_URL
          tar -xvf openwrt-sdk-*.tar.xz
          mv openwrt-sdk-* openwrt-sdk

          # 关键步骤：将自定义包目录软链接到 SDK 的标准位置
          ln -s $(pwd)/openwrt-sdk/package ./package

      - name: Prepare PPTP source
        run: |
          # 复制源码到 SDK 的 dl 目录
          mkdir -p openwrt-sdk/dl/
          chmod 755 openwrt-sdk/dl/
          cp pptp-linux_1.10.0.orig.tar.gz openwrt-sdk/dl/

          # 确保 Config.in 和 Makefile 存在
          ls -l openwrt-sdk/package/pptp-linux/

      - name: Compile IPK
        run: |
          cd openwrt-sdk
          echo "src-link custom $(pwd)/package" >> feeds.conf.default

          # 更新并安装 feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          # 强制包含自定义包配置
          make defconfig
          echo "CONFIG_PACKAGE_pptp-linux=y" >> .config
          make package/pptp-linux/compile V=s

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: pptp-ipk
          path: openwrt-sdk/bin/packages/mipsel_24kc/base/pptp-linux_*.ipk
