name: Build PPTP IPK

on:
  push:
    branches: [ main ]

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OpenWrt SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev unzip python3
          
          # 下载 OpenWrt SDK（以 21.02.7/mipsel_24kc 为例）
          SDK_URL="https://downloads.openwrt.org/releases/21.02.7/targets/ramips/mt7621/openwrt-sdk-21.02.7-ramips-mt7621_gcc-8.4.0_musl.Linux-x86_64.tar.xz"

          # 添加重试与校验（网页8建议）
          wget --retry-connrefused --waitretry=30 $SDK_URL
          sha256sum openwrt-sdk-*.tar.xz | grep -q "ceed7c1869a373b23ff2826ccce587723b0a0bcf8ce9bfa377557c705a41638a" || (echo "文件校验失败"; exit 1)
          # 直接解压到目标目录（避免mv操作）
          mkdir -p openwrt-sdk
          tar -xvf openwrt-sdk-*.tar.xz -C openwrt-sdk --strip-components 1

          # 修复权限问题（网页3/8方案）
          sudo chown -R $USER:$USER openwrt-sdk
          find openwrt-sdk -type d -exec chmod 755 {} \;


          
          # 解压并重命名目录（精确匹配）
          #tar -xvf openwrt-sdk-21.02.7-ramips-mt7621_gcc-8.4.0_musl.Linux-x86_64.tar.xz
          #mv openwrt-sdk-21.02.7-ramips-mt7621_gcc-8.4.0_musl.Linux-x86_64 openwrt-sdk
          
          # 验证 SDK 完整性
          if [ ! -f "openwrt-sdk/scripts/feeds" ]; then
            echo "Error: SDK is missing critical files!"
            exit 1
          fi

      - name: Prepare PPTP source
        run: |
          # 复制源码到 SDK 的 dl 目录
          mkdir -p openwrt-sdk/dl
          if [ ! -f "pptp-linux_1.10.0.orig.tar.gz" ]; then
           wget https://deb.sipwise.com/debian/pool/main/p/pptp-linux/pptp-linux_1.10.0.orig.tar.gz
          fi
          cp pptp-linux_1.10.0.orig.tar.gz openwrt-sdk/dl/
          # 复制包定义到 SDK 的 package 目录
          mkdir -p openwrt-sdk/package/pptp-linux
          cp -r package/pptp-linux/* openwrt-sdk/package/pptp-linux/
          
          # 调试：查看目录结构
          ls -lR openwrt-sdk/package/pptp-linux

      - name: Compile IPK
        run: |
          cd openwrt-sdk
          ./scripts/feeds install automake libtool
          make defconfig
          make package/pptp-linux/compile V=s

      - name: Debug IPK files
        run: ls -lR ${{ github.workspace }}/openwrt-sdk/bin

      
      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: pptp-ipk
          path: ${{ github.workspace }}/openwrt-sdk/bin/**/pptp-linux_*.ipk
          if-no-files-found: error  # 强制报错而非警告
          retention-days: 7
